name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to environment'
        type: environment
        required: true
#        type: choice
#        options:
#          - staging
#          - acceptance
#          - production

jobs:
  build-staging:
    if:  ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name:
        run: echo ${{ github.event.inputs.environment }}

  build-acceptance:
    if:  ${{ inputs.environment == 'acceptance' }}
    runs-on: ubuntu-latest
    environment: acceptance
    steps:
      - name:
        run: echo ${{ github.event.inputs.environment }}

  build-production:
    if:  ${{ inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name:
        run: echo ${{ github.event.inputs.environment }}
